// Dummy data for the HRMS platform

export const dummyUsers = {
  admin: {
    id: "1",
    email: "admin@averpeople.com",
    password: "admin123",
    name: "Sarah Johnson",
    role: "admin",
    avatar: "/professional-woman-avatar.png",
    department: "Human Resources",
    designation: "HR Director",
  },
  hr: {
    id: "2",
    email: "hr@averpeople.com",
    password: "hr123",
    name: "Michael Chen",
    role: "hr",
    avatar: "/professional-man-avatar.png",
    department: "Human Resources",
    designation: "HR Manager",
  },
  manager: {
    id: "3",
    email: "manager@averpeople.com",
    password: "manager123",
    name: "Emily Davis",
    role: "manager",
    avatar: "/business-woman-avatar.png",
    department: "Engineering",
    designation: "Engineering Manager",
  },
  employee: {
    id: "4",
    email: "employee@averpeople.com",
    password: "employee123",
    name: "James Wilson",
    role: "employee",
    avatar: "/young-professional-man-avatar.png",
    department: "Engineering",
    designation: "Software Engineer",
  },
}

export const employees = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah.johnson@averpeople.com",
    department: "Human Resources",
    designation: "HR Director",
    status: "active",
    joinDate: "2020-03-15",
    phone: "+1 555-0101",
    avatar: "/professional-woman-diverse.png",
    salary: 95000,
    location: "New York",
  },
  {
    id: "2",
    name: "Michael Chen",
    email: "michael.chen@averpeople.com",
    department: "Engineering",
    designation: "Senior Developer",
    status: "active",
    joinDate: "2021-06-20",
    phone: "+1 555-0102",
    avatar: "/asian-man-developer.png",
    salary: 120000,
    location: "San Francisco",
  },
  {
    id: "3",
    name: "Emily Davis",
    email: "emily.davis@averpeople.com",
    department: "Marketing",
    designation: "Marketing Manager",
    status: "active",
    joinDate: "2019-11-10",
    phone: "+1 555-0103",
    avatar: "/marketing-professional-woman.png",
    salary: 85000,
    location: "Chicago",
  },
  {
    id: "4",
    name: "James Wilson",
    email: "james.wilson@averpeople.com",
    department: "Sales",
    designation: "Sales Executive",
    status: "active",
    joinDate: "2022-01-05",
    phone: "+1 555-0104",
    avatar: "/sales-professional-man.png",
    salary: 75000,
    location: "Boston",
  },
  {
    id: "5",
    name: "Lisa Anderson",
    email: "lisa.anderson@averpeople.com",
    department: "Finance",
    designation: "Financial Analyst",
    status: "active",
    joinDate: "2021-09-12",
    phone: "+1 555-0105",
    avatar: "/finance-professional-woman.jpg",
    salary: 88000,
    location: "New York",
  },
  {
    id: "6",
    name: "Robert Brown",
    email: "robert.brown@averpeople.com",
    department: "Engineering",
    designation: "DevOps Engineer",
    status: "on-leave",
    joinDate: "2020-07-22",
    phone: "+1 555-0106",
    avatar: "/devops-engineer-man.jpg",
    salary: 110000,
    location: "Seattle",
  },
  {
    id: "7",
    name: "Amanda Martinez",
    email: "amanda.martinez@averpeople.com",
    department: "Design",
    designation: "UI/UX Designer",
    status: "active",
    joinDate: "2022-04-18",
    phone: "+1 555-0107",
    avatar: "/designer-woman-creative.jpg",
    salary: 92000,
    location: "Los Angeles",
  },
  {
    id: "8",
    name: "David Kim",
    email: "david.kim@averpeople.com",
    department: "Engineering",
    designation: "Frontend Developer",
    status: "active",
    joinDate: "2023-02-14",
    phone: "+1 555-0108",
    avatar: "/frontend-developer-asian.jpg",
    salary: 95000,
    location: "Austin",
  },
]

export const departments = [
  { id: "1", name: "Human Resources", headCount: 12, budget: 450000 },
  { id: "2", name: "Engineering", headCount: 45, budget: 2500000 },
  { id: "3", name: "Marketing", headCount: 18, budget: 800000 },
  { id: "4", name: "Sales", headCount: 32, budget: 1200000 },
  { id: "5", name: "Finance", headCount: 15, budget: 600000 },
  { id: "6", name: "Design", headCount: 10, budget: 400000 },
  { id: "7", name: "Operations", headCount: 22, budget: 700000 },
]

export const attendanceRecords = [
  {
    id: "1",
    employeeId: "2",
    employeeName: "Michael Chen",
    date: "2024-12-02",
    checkIn: "09:02",
    checkOut: "18:15",
    status: "present",
    type: "biometric",
    location: { lat: 37.7749, lng: -122.4194 },
    workHours: 9.22,
  },
  {
    id: "2",
    employeeId: "3",
    employeeName: "Emily Davis",
    date: "2024-12-02",
    checkIn: "08:45",
    checkOut: "17:30",
    status: "present",
    type: "face-recognition",
    location: { lat: 41.8781, lng: -87.6298 },
    workHours: 8.75,
  },
  {
    id: "3",
    employeeId: "4",
    employeeName: "James Wilson",
    date: "2024-12-02",
    checkIn: "09:30",
    checkOut: "18:45",
    status: "late",
    type: "geo-fence",
    location: { lat: 42.3601, lng: -71.0589 },
    workHours: 9.25,
  },
  {
    id: "4",
    employeeId: "5",
    employeeName: "Lisa Anderson",
    date: "2024-12-02",
    checkIn: null,
    checkOut: null,
    status: "absent",
    type: null,
    location: null,
    workHours: 0,
  },
  {
    id: "5",
    employeeId: "6",
    employeeName: "Robert Brown",
    date: "2024-12-02",
    checkIn: null,
    checkOut: null,
    status: "on-leave",
    type: null,
    location: null,
    workHours: 0,
  },
]

export const leaveRequests = [
  {
    id: "1",
    employeeId: "2",
    employeeName: "Michael Chen",
    type: "Annual Leave",
    startDate: "2024-12-15",
    endDate: "2024-12-20",
    days: 6,
    status: "pending",
    reason: "Family vacation",
  },
  {
    id: "2",
    employeeId: "6",
    employeeName: "Robert Brown",
    type: "Sick Leave",
    startDate: "2024-12-01",
    endDate: "2024-12-05",
    days: 5,
    status: "approved",
    reason: "Medical treatment",
  },
  {
    id: "3",
    employeeId: "7",
    employeeName: "Amanda Martinez",
    type: "Personal Leave",
    startDate: "2024-12-10",
    endDate: "2024-12-11",
    days: 2,
    status: "pending",
    reason: "Personal matters",
  },
]

export const courses = [
  {
    id: "1",
    title: "Leadership Excellence Program",
    description: "Develop essential leadership skills for modern managers",
    category: "Leadership",
    duration: "8 hours",
    modules: 12,
    enrolled: 45,
    rating: 4.8,
    instructor: "Dr. Sarah Mitchell",
    progress: 65,
    image: "/leadership-training-workshop.png",
    level: "Intermediate",
    points: 500,
  },
  {
    id: "2",
    title: "Advanced Project Management",
    description: "Master agile and traditional project management methodologies",
    category: "Management",
    duration: "12 hours",
    modules: 18,
    enrolled: 78,
    rating: 4.6,
    instructor: "Prof. David Lee",
    progress: 30,
    image: "/project-management-teamwork.png",
    level: "Advanced",
    points: 750,
  },
  {
    id: "3",
    title: "Data Analytics Fundamentals",
    description: "Learn to analyze and visualize business data effectively",
    category: "Technical",
    duration: "10 hours",
    modules: 15,
    enrolled: 120,
    rating: 4.9,
    instructor: "Emma Thompson",
    progress: 0,
    image: "/data-analytics-visualization.png",
    level: "Beginner",
    points: 600,
  },
  {
    id: "4",
    title: "Effective Communication Skills",
    description: "Enhance your workplace communication and presentation abilities",
    category: "Soft Skills",
    duration: "6 hours",
    modules: 8,
    enrolled: 95,
    rating: 4.7,
    instructor: "Mark Johnson",
    progress: 100,
    image: "/communication-skills.png",
    level: "Beginner",
    points: 400,
  },
  {
    id: "5",
    title: "Cybersecurity Awareness",
    description: "Protect your organization from cyber threats",
    category: "Technical",
    duration: "4 hours",
    modules: 6,
    enrolled: 200,
    rating: 4.5,
    instructor: "Alex Rivera",
    progress: 85,
    image: "/cybersecurity-network.png",
    level: "Beginner",
    points: 300,
  },
]

export const leaderboard = [
  { rank: 1, name: "Michael Chen", points: 2450, level: "Expert", badges: 12, avatar: "/asian-man-developer.png" },
  { rank: 2, name: "Emily Davis", points: 2280, level: "Expert", badges: 10, avatar: "/marketing-woman.png" },
  { rank: 3, name: "Amanda Martinez", points: 2100, level: "Pro", badges: 9, avatar: "/stylish-woman.png" },
  { rank: 4, name: "David Kim", points: 1950, level: "Pro", badges: 8, avatar: "/frontend-developer-workspace.png" },
  {
    rank: 5,
    name: "James Wilson",
    points: 1820,
    level: "Intermediate",
    badges: 7,
    avatar: "/friendly-salesman.png",
  },
]

export const badges = [
  { id: "1", name: "Quick Learner", icon: "⚡", description: "Complete 5 courses", earned: true },
  { id: "2", name: "Perfect Score", icon: "🎯", description: "Score 100% in any assessment", earned: true },
  { id: "3", name: "Streak Master", icon: "🔥", description: "Maintain 30-day learning streak", earned: false },
  { id: "4", name: "Team Player", icon: "🤝", description: "Complete 3 group activities", earned: true },
  { id: "5", name: "Knowledge Seeker", icon: "📚", description: "Enroll in 10 courses", earned: false },
]

export const interviews = [
  {
    id: "1",
    candidateName: "John Smith",
    position: "Senior Frontend Developer",
    department: "Engineering",
    scheduledDate: "2024-12-05",
    scheduledTime: "10:00 AM",
    status: "completed",
    aiScore: 85,
    communicationScore: 88,
    technicalScore: 82,
    confidenceScore: 90,
    recommendation: "Strong Hire",
    avatar: "/candidate-man-professional.jpg",
  },
  {
    id: "2",
    candidateName: "Maria Garcia",
    position: "Product Manager",
    department: "Product",
    scheduledDate: "2024-12-06",
    scheduledTime: "2:00 PM",
    status: "scheduled",
    aiScore: null,
    communicationScore: null,
    technicalScore: null,
    confidenceScore: null,
    recommendation: null,
    avatar: "/candidate-woman-latina.jpg",
  },
  {
    id: "3",
    candidateName: "Alex Turner",
    position: "Data Scientist",
    department: "Analytics",
    scheduledDate: "2024-12-04",
    scheduledTime: "11:30 AM",
    status: "completed",
    aiScore: 72,
    communicationScore: 75,
    technicalScore: 78,
    confidenceScore: 68,
    recommendation: "Consider",
    avatar: "/candidate-man-data-scientist.jpg",
  },
  {
    id: "4",
    candidateName: "Sophie Williams",
    position: "UX Designer",
    department: "Design",
    scheduledDate: "2024-12-07",
    scheduledTime: "3:30 PM",
    status: "in-progress",
    aiScore: null,
    communicationScore: null,
    technicalScore: null,
    confidenceScore: null,
    recommendation: null,
    avatar: "/candidate-woman-designer.jpg",
  },
]

export const payrollData = [
  {
    id: "1",
    employeeId: "2",
    employeeName: "Michael Chen",
    department: "Engineering",
    month: "November 2024",
    basicSalary: 8000,
    hra: 2400,
    transportAllowance: 500,
    medicalAllowance: 300,
    specialAllowance: 800,
    grossSalary: 12000,
    pf: 960,
    tax: 1800,
    professionalTax: 200,
    esi: 0,
    totalDeductions: 2960,
    netSalary: 9040,
    status: "paid",
    paymentDate: "2024-11-30",
  },
  {
    id: "2",
    employeeId: "3",
    employeeName: "Emily Davis",
    department: "Marketing",
    month: "November 2024",
    basicSalary: 6000,
    hra: 1800,
    transportAllowance: 400,
    medicalAllowance: 300,
    specialAllowance: 583,
    grossSalary: 9083,
    pf: 720,
    tax: 1200,
    professionalTax: 200,
    esi: 68,
    totalDeductions: 2188,
    netSalary: 6895,
    status: "paid",
    paymentDate: "2024-11-30",
  },
  {
    id: "3",
    employeeId: "4",
    employeeName: "James Wilson",
    department: "Sales",
    month: "December 2024",
    basicSalary: 5000,
    hra: 1500,
    transportAllowance: 350,
    medicalAllowance: 250,
    specialAllowance: 650,
    grossSalary: 7750,
    pf: 600,
    tax: 800,
    professionalTax: 200,
    esi: 58,
    totalDeductions: 1658,
    netSalary: 6092,
    status: "pending",
    paymentDate: null,
  },
]

export const reimbursements = [
  {
    id: "1",
    employeeId: "2",
    employeeName: "Michael Chen",
    type: "Travel",
    amount: 450,
    date: "2024-11-25",
    status: "approved",
    description: "Client meeting travel expenses",
  },
  {
    id: "2",
    employeeId: "4",
    employeeName: "James Wilson",
    type: "Meal",
    amount: 85,
    date: "2024-11-28",
    status: "pending",
    description: "Client dinner expenses",
  },
  {
    id: "3",
    employeeId: "7",
    employeeName: "Amanda Martinez",
    type: "Equipment",
    amount: 250,
    date: "2024-11-20",
    status: "approved",
    description: "Design software subscription",
  },
]

export const dashboardStats = {
  totalEmployees: 156,
  presentToday: 142,
  onLeave: 8,
  newJoinees: 5,
  pendingApprovals: 12,
  activeTrainings: 8,
  upcomingInterviews: 15,
  payrollProcessed: 98.5,
}

export const geoFenceLocations = [
  { id: "1", name: "HQ Office - New York", lat: 40.7128, lng: -74.006, radius: 100 },
  { id: "2", name: "Tech Hub - San Francisco", lat: 37.7749, lng: -122.4194, radius: 150 },
  { id: "3", name: "Sales Office - Chicago", lat: 41.8781, lng: -87.6298, radius: 100 },
  { id: "4", name: "Client Site - Boston", lat: 42.3601, lng: -71.0589, radius: 200 },
]

export const certificates = [
  {
    id: "CERT-2024-001",
    employeeName: "Michael Chen",
    courseName: "Leadership Excellence Program",
    issueDate: "2024-10-15",
    validUntil: "2027-10-15",
    score: 92,
    hashId: "0x7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069",
    qrCode: "https://verify.averpeople.com/cert/CERT-2024-001",
  },
  {
    id: "CERT-2024-002",
    employeeName: "Emily Davis",
    courseName: "Advanced Project Management",
    issueDate: "2024-11-20",
    validUntil: "2027-11-20",
    score: 88,
    hashId: "0x3b2c5d8a9f1e4c7b6a0d3e5f8c9b1a2d4e6f8a0c2e4b6d8f0a2c4e6b8d0f2a4c6",
    qrCode: "https://verify.averpeople.com/cert/CERT-2024-002",
  },
]
